default_stages: [push, commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude: '^.*\.(tsv|json|svg)'
      - id: end-of-file-fixer
        exclude: '^.*\.(tsv|json|svg)'
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: black
        name: Black formatter
        entry: black --check
        language: system
        require_serial: true
        types: [python]
      - id: isort
        name: Sorting Python imports
        entry: isort --check
        language: system
        types: [python]
      - id: pytestnow
        name: Check that no tests marked with 'now' exist
        entry: "@pytest.mark.now"
        language: pygrep
        types: [python]
      - id: django-migrations
        name: Check django migrations
        entry: python manage.py makemigrations --check --no-input
        language: system
        types: [python]
        pass_filenames: false
