# Generated by Django 4.0.4 on 2022-05-06 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_extensions.db.fields

import apps.game.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "uid",
                    models.CharField(max_length=36, unique=True, verbose_name="UID"),
                ),
                ("version", models.CharField(max_length=16, verbose_name="version")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="difficulty"
                    ),
                ),
                (
                    "xp_minimum",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="XP minimum"
                    ),
                ),
                (
                    "xp_modifier",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="XP modifier"
                    ),
                ),
                (
                    "community",
                    models.BooleanField(default=False, verbose_name="community"),
                ),
                (
                    "date_approved",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date approved"
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(
                        blank=True,
                        upload_to=apps.game.models.zip_file_path,
                        verbose_name="ZIP file",
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=list, verbose_name="data"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approved by",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.language",
                        to_field="code",
                        verbose_name="language",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
    ]
